/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;
import servicos.ServicoSalarioMensal;
import servicos.ServicoSig;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import classes.Funcionario;
import classes.SalarioMensal;
import javax.swing.JComboBox;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.event.ActionListener;
/**
 *
 * @author raquel.silva2
 */
public class Fsig extends javax.swing.JFrame {

    /**
     * Creates new form SIG
     */
    public Fsig() {
        initComponents();
    }

    ServicoSig sig = new ServicoSig();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLucroSemContratar = new javax.swing.JButton();
        btnLucroContratandoFuncionario = new javax.swing.JButton();
        btnLucroAtual = new javax.swing.JButton();
        btnAplicacao = new javax.swing.JButton();
        btnAplicacao.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SIG");

        jLucroSemContratar.setText(" O lucro da fabrica sem contratar um novo funcionario");
        
        jLucroSemContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jLucroSemContratarActionPerformed(evt);
				} catch (HeadlessException | SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnLucroContratandoFuncionario.setText(" O lucro da fabrica se contratar um novo funcionario");
        btnLucroContratandoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					LucroContratando(evt);
				} catch (HeadlessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnLucroAtual.setText(" O lucro atual");
        btnLucroAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton3ActionPerformed(evt);
				} catch (HeadlessException | SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnAplicacao.setText(" Investimento em aplicacao");
//        btnAplicacao.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                try {
//					Aplicacao(evt);
//				} catch (HeadlessException | SQLException e) {
//					// TODO Auto-generated catch block
//					e.printStackTrace();
//				}
//            }
//
//			private void Aplicacao(ActionEvent evt) {
//				//TO DO
//			}
//        });
        JLabel jLabel2 = new JLabel();
        jLabel2.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(43)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jComboBoxMes, 0, 499, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(42)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLucroSemContratar, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        						.addComponent(btnLucroContratandoFuncionario, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        						.addComponent(btnLucroAtual, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        						.addComponent(btnAplicacao, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))))
        			.addGap(50))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(300)
        			.addComponent(jLabel1)
        			.addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(21)
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBoxMes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(38)
        			.addComponent(jLucroSemContratar)
        			.addGap(18)
        			.addComponent(btnLucroContratandoFuncionario)
        			.addGap(18)
        			.addComponent(btnLucroAtual)
        			.addGap(18)
        			.addComponent(btnAplicacao)
        			.addContainerGap(42, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
        
        this.carregarListMes();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLucroSemContratarActionPerformed(java.awt.event.ActionEvent evt) throws HeadlessException, SQLException {//GEN-FIRST:event_jLucroSemContratarActionPerformed
    	String dataSelecionada = (String) jComboBoxMes.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Lucro Sem contratar: " + sig.lucroSemContratar(dataSelecionada));
    }//GEN-LAST:event_jLucroSemContratarActionPerformed

    private void LucroContratando(java.awt.event.ActionEvent evt) throws HeadlessException, SQLException {//GEN-FIRST:event_jButton2ActionPerformed
    	String dataSelecionada = (String) jComboBoxMes.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Lucro contratando: " + sig.lucroSemContratar(dataSelecionada));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws HeadlessException, SQLException{

    	String dataSelecionada = (String) jComboBoxMes.getSelectedItem();
		JOptionPane.showMessageDialog(null, "Valor do lucro atual: " + sig.faturamento(dataSelecionada));
    	
    }
    
    private void carregarListMes() {
    	
    	ArrayList<String> lista = new ArrayList<>();
        
        if (jComboBoxMes.getItemCount() > 0){
        	jComboBoxMes.removeAllItems();
        }
        
        try {
            lista = servicoSalarioMensal.getDatas();
        } catch (SQLException ex) {
            Logger.getLogger(Fsig.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        lista.forEach((u) -> {
        	jComboBoxMes.addItem(u);
        }); 
        
        jComboBoxMes.setSelectedIndex(-1);
    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fsig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fsig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fsig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fsig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fsig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLucroContratandoFuncionario;
    private javax.swing.JButton btnLucroAtual;
    private javax.swing.JButton btnAplicacao;
    private javax.swing.JLabel jLabel1;
    private JComboBox<String> jComboBoxMes = new JComboBox<String>();
    private javax.swing.JButton jLucroSemContratar;
    private ServicoSalarioMensal servicoSalarioMensal = new ServicoSalarioMensal();
}
