/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author matheus.aviz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    FCadFuncionario fcadfuncionario;
    FCalcSalarioMensal fcalcsalariomensal;
    FConsultSalariobyMes fconsultsalario;
    Fsig sig;
    FGrafico grafico;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCadSalario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jGastoMensal = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuSIG = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastrar");

        jMenuItem1.setText("Funcionario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jCadSalario.setText("Salario Mensal");
        jCadSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadSalarioActionPerformed(evt);
            }
        });
        jMenu1.add(jCadSalario);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consultar");

        jGastoMensal.setText("Gasto Mensal");
        jGastoMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGastoMensalActionPerformed(evt);
            }
        });
        jMenu4.add(jGastoMensal);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("SIG");
        jMenu5.setToolTipText("");

        jMenuSIG.setText("Menu SIG");
        jMenuSIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSIGActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuSIG);
        jMenuSIG.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);
        
        jGrafico = new JMenu();
        jGrafico.setToolTipText("");
        jGrafico.setText("Consultar grafico");
        jMenuBar1.add(jGrafico);
        
        jgrafico1 = new JMenuItem();
        jgrafico1.setText("Grafico");
        jGrafico.add(jgrafico1);
        jgrafico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	System.out.println("a");
            	GraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (fcadfuncionario == null){
            fcadfuncionario = new FCadFuncionario();
    }
        fcadfuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jGastoMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGastoMensalActionPerformed
        if (fconsultsalario == null){
            fconsultsalario = new FConsultSalariobyMes();
    }
        fconsultsalario.setVisible(true);
    }//GEN-LAST:event_jGastoMensalActionPerformed

    private void jCadSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadSalarioActionPerformed
        if (fcalcsalariomensal == null){
            fcalcsalariomensal = new FCalcSalarioMensal();
    }
        fcalcsalariomensal.setVisible(true);
    }//GEN-LAST:event_jCadSalarioActionPerformed

    private void jMenuSIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSIGActionPerformed
            if (sig == null){
            sig = new Fsig();
    }
        sig.setVisible(true);
    }//GEN-LAST:event_jMenuSIGActionPerformed
    
    private void GraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSIGActionPerformed
        if (grafico == null){
        	grafico = new FGrafico();
}
        grafico.setVisible(true);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadSalario;
    private javax.swing.JMenuItem jGastoMensal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuSIG;
    private JMenu jGrafico;
    private JMenuItem jgrafico1;
    // End of variables declaration//GEN-END:variables
}
